# Generated by Django 6.0.5 on 2026-06-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(related_name='issues', to='issues.type', verbose_name='Тип'),
        ),
    ]
