# Generated by Django 6.0.5 on 2026-06-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_project_issue_project'),
    ]

    operations = [
    ]
