# Generated by Django 6.0.5 on 2026-06-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_project_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('manage_members', 'Can manage project members')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
